
inventory:
    plugin: SimpleInventory
    options:
        host_file: "Z:/Scripts/Python2/hosts.yaml"
        group_file: "Z:/Scripts/Python2/groups.yaml"
        defaults_file: "Z:/Scripts/Python2/defaults.yaml"

